### PR TITLE
Update to v0.1.8

### PR DESCRIPTION
**Pull request by proinsias**

### CODE REVIEW

**Comment by pmlandwehr** [comment]
Hmm. Rebuilding Windows CI...

**Comment by proinsias** [comment]
Rebuilding AppVeyor.

**Comment by pmlandwehr** [comment]
AppVeyor once again...

**Comment by jakirkham** [comment]
Please try rebasing on `master`, @proinsias . I think it is not picking up the changes from the 1.3.3 re-rendering that are in `master`.

**Comment by proinsias** [comment]
@jakirkham – I tried that, but still no luck.

**Comment by jakirkham** [comment]
There have been a number of `conda-smithy` release since then. Could you please try [re-rendering]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with a newer version (`1.4.4`?)?

**Pull request merged**
