### PR TITLE
Update version to v0.1.12

### PR DESCRIPTION
**Pull request by tkelman**
Anything else needed here, aside from waiting for CI? Thanks in advance!

### CODE REVIEW

**Comment by tkelman** [comment]
Not sure what's up with that appveyor failure, so let's try this:

@conda-forge-admin, please rerender

**Comment by tkelman** [comment]
Only took a week or two to get through the travis queue, but finally green. cc @pmlandwehr @proinsias.

I also realized that the pypi wheel of this is noarch, so maybe it's also worth making that change here so it goes through faster next time.

**Comment by tkelman** [comment]
@isuruf can you assist here too? we can maybe make this noarch, and add to maintainers, in a future PR. much appreciated

**Comment by isuruf** [comment]
Can't make this noarch because there are selectors (futures for py2k only) and conda doesn't support selectors in noarch packages yet.

**Comment by isuruf** [comment]
Please send a PR with `[skip ci]` to add yourself as a maintainer

**Comment by tkelman** [comment]
I see, thanks

**Comment by tkelman** [comment]
> Please send a PR with `[skip ci]` to add yourself as a maintainer

Done in #12. Do permissions get dealt with automatically by a bot?

**Comment by isuruf** [comment]
> Do permissions get dealt with automatically by a bot?

Yes, once it's merged, permissions are added.

**Pull request merged**
